### ISSUE TITLE
NoSuchMethodError when using Maven dependency

### ISSUE THREAD

**Issue by jovankricka** [vinsguru/pdf-util#4]
When I include PDFUtil as a maven dependency with:

```
<dependency>
    <groupId>com.testautomationguru.pdfutil</groupId>
    <artifactId>pdf-util</artifactId>
    <version>0.0.1</version>
</dependency>
```

I get following error:

> java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.getPage(I)Lorg/apache/pdfbox/pdmodel/PDPage;
> 	at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:108)
> 	at org.apache.pdfbox.rendering.PDFRenderer.renderImageWithDPI(PDFRenderer.java:94)
> 	at com.testautomationguru.utility.PDFUtil.convertToImageAndCompare(PDFUtil.java:470)
> 	at com.testautomationguru.utility.PDFUtil.comparePdfByImage(PDFUtil.java:443)
> 	at com.testautomationguru.utility.PDFUtil.comparePdfFiles(PDFUtil.java:304)
> 	at com.testautomationguru.utility.PDFUtil.compare(PDFUtil.java:264)
> 

When I just add the pdfutil.jar to my project it works fine.

**Comment by jovankricka** [comment]
I had pdfbox-app maven dependency in my pom file:
```
<dependency>
    <groupId>org.apache.pdfbox</groupId>
    <artifactId>pdfbox-app</artifactId>
    <version>1.8.9</version>
</dependency>
```
I removed it and now it works fine.
